"""empty message

Revision ID: 7b657611013f
Revises: d3c94f83d3e3
Create Date: 2021-09-17 09:50:43.194609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b657611013f'
down_revision = 'd3c94f83d3e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'about_me', 'user', ['use_id'], ['id'])
    op.drop_column('about_me', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about_me', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'about_me', type_='foreignkey')
    # ### end Alembic commands ###
